adding:
  dependencies:
    config:
      - field.field.node.page.field_banner
    module:
      - paragraphs
  content:
    field_banner:
      type: paragraphs
      weight: 121
      region: content
      settings:
        title: Paragraph
        title_plural: Paragraphs
        edit_mode: open
        closed_mode: summary
        autocollapse: none
        closed_mode_threshold: 0
        add_mode: dropdown
        form_display_mode: default
        default_paragraph_type: ''
        features:
          collapse_edit_all: collapse_edit_all
          duplicate: duplicate
      third_party_settings: {  }
removing: {  }
