adding:
  dependencies:
    config:
      - field.field.node.products.field_gallery
      - field.field.node.products.field_product_banner
    module:
      - entity_reference_revisions
  content:
    field_gallery:
      type: entity_reference_revisions_entity_view
      label: above
      settings:
        view_mode: default
        link: ''
      third_party_settings: {  }
      weight: 104
      region: content
    field_product_banner:
      type: entity_reference_revisions_entity_view
      label: above
      settings:
        view_mode: default
        link: ''
      third_party_settings: {  }
      weight: 102
      region: content
removing: {  }
