adding:
  dependencies:
    config:
      - field.field.node.products.field_gallery
      - field.field.node.products.field_product_banner
    module:
      - paragraphs
  content:
    field_gallery:
      type: paragraphs
      weight: 124
      region: content
      settings:
        title: Paragraph
        title_plural: Paragraphs
        edit_mode: open
        closed_mode: summary
        autocollapse: none
        closed_mode_threshold: 0
        add_mode: dropdown
        form_display_mode: default
        default_paragraph_type: ''
        features:
          collapse_edit_all: collapse_edit_all
          duplicate: duplicate
      third_party_settings: {  }
    field_product_banner:
      type: paragraphs
      weight: 122
      region: content
      settings:
        title: Paragraph
        title_plural: Paragraphs
        edit_mode: open
        closed_mode: summary
        autocollapse: none
        closed_mode_threshold: 0
        add_mode: dropdown
        form_display_mode: default
        default_paragraph_type: ''
        features:
          collapse_edit_all: collapse_edit_all
          duplicate: duplicate
      third_party_settings: {  }
removing: {  }
